import numpy as np
import matplotlib.pyplot as plt


def generate_data():
    """
        Generates time series data for two elements
        dependent on the following equations:
        y2(t) = y1(t-1) + μ1
        y1(t) = α1 y1(t-1) + α2 y2(t-1) + μ2

        where  μi ~ Normal(0,σ2)
    :return:
    """
    pass


def plot_time_series_data(data):
    """
        Plots data generated by the above process
    :param data: Data to be plotted
    :return: None
    """
    pass


if __name__ == '__main__':
    pass
